import React, { useEffect, useState } from 'react';
import { Lightbulb, Info, Award, ExternalLink, GraduationCap, Scale } from 'lucide-react';
import api from '../services/api';
import { HistoryEntry, AnalysisResponse } from '../types';

interface CircularInnovationProps {
  latestAnalysis: AnalysisResponse | null;
  company: string;
}

export const CircularInnovation: React.FC<CircularInnovationProps> = ({ latestAnalysis, company }) => {
  const [history, setHistory] = useState<HistoryEntry[]>([]);
  const [selectedTx, setSelectedTx] = useState('');
  const [activeAnalysis, setActiveAnalysis] = useState<AnalysisResponse | null>(latestAnalysis);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const loadHistory = async () => {
      try {
        const res = await api.getHistory(company);
        setHistory(res);
        if (res.length > 0 && !latestAnalysis) {
          setSelectedTx(res[0].contract_id);
        }
      } catch (err) {
        console.error(err);
      }
    };
    loadHistory();
  }, [company, latestAnalysis]);

  useEffect(() => {
    if (latestAnalysis) {
      setActiveAnalysis(latestAnalysis);
    }
  }, [latestAnalysis]);

  const handleLoadTx = async () => {
    if (!selectedTx) return;
    setLoading(true);
    try {
      const match = history.find((h) => h.contract_id === selectedTx);
      if (match) {
        const form = new FormData();
        form.append('material_type', match.material_type);
        form.append('quantity', String(match.quantity_kg / 1000.0));
        form.append('location', 'Tiruppur');
        form.append('industry', 'Textile');
        form.append('description', 'Recovered transaction.');
        form.append('company_name', company);
        const detailed = await api.analyzeWaste(form);
        setActiveAnalysis(detailed);
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-8 animate-fade-in">
      {/* Title */}
      <div>
        <h1 className="text-3xl font-extrabold tracking-tight text-text-primary">
          Circular Innovation Discoveries
        </h1>
        <p className="text-text-secondary mt-1">
          Explore research paper validations and patent claims generated by literature lookup modules.
        </p>
      </div>

      {/* History Selector if no active analysis */}
      {!latestAnalysis && history.length > 0 && (
        <div className="bg-white rounded-2xl p-6 shadow-card border border-gray-100/50 flex flex-wrap items-center gap-4">
          <label className="text-sm font-semibold text-text-secondary">
            Select contract from ESG ledger:
          </label>
          <select
            value={selectedTx}
            onChange={(e) => setSelectedTx(e.target.value)}
            className="text-sm bg-gray-50 border border-gray-200 rounded-lg p-2.5 text-text-primary outline-none"
          >
            {history.map((h) => (
              <option key={h.contract_id} value={h.contract_id}>
                {h.contract_id} - {h.material_type.charAt(0).toUpperCase() + h.material_type.slice(1)} ({h.quantity_kg} kg)
              </option>
            ))}
          </select>
          <button
            onClick={handleLoadTx}
            disabled={loading}
            className="bg-primary-green hover:bg-primary-hover text-white font-bold text-sm py-2.5 px-4 rounded-xl transition-colors"
          >
            {loading ? 'Retrieving innovations...' : 'Fetch Innovation Discoveries'}
          </button>
        </div>
      )}

      {activeAnalysis ? (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Main list of discoveries */}
          <div className="lg:col-span-2 space-y-6">
            <div className="bg-white rounded-2xl p-6 shadow-card border border-gray-100/50">
              <h3 className="font-bold text-lg text-text-primary mb-6 flex items-center gap-2">
                <Lightbulb className="text-primary-green" size={20} />
                Evidence-Backed Pathways
              </h3>

              <div className="space-y-6">
                {activeAnalysis.circular_innovation.discoveries.map((disc) => (
                  <div
                    key={disc.innovation_id}
                    className="p-5 border border-gray-150 rounded-2xl bg-gray-50/40 space-y-4 hover:shadow-lg transition-shadow"
                  >
                    <div className="flex justify-between items-start">
                      <div>
                        <div className="flex items-center gap-2">
                          <span className="text-xs font-mono font-bold text-text-muted">
                            {disc.innovation_id}
                          </span>
                          <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-emerald-50 text-emerald-700">
                            TRL {disc.trl_level}
                          </span>
                          <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-blue-50 text-blue-700">
                            {disc.novelty_index}
                          </span>
                        </div>
                        <h4 className="font-extrabold text-base text-text-primary mt-1">
                          {disc.title}
                        </h4>
                      </div>
                      <span className="text-xs font-black bg-emerald-50 text-emerald-600 px-2 py-1 rounded">
                        Score: {disc.score.toFixed(1)}/100
                      </span>
                    </div>

                    <div className="space-y-1.5 text-xs text-text-secondary leading-relaxed">
                      <p>
                        <strong className="text-text-primary">Transformation Pathway:</strong> {disc.transformation_pathway}
                      </p>
                      <p className="mt-1">
                        <strong className="text-text-primary">TRL Stage Details:</strong> {disc.trl_description}
                      </p>
                    </div>

                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-4 border-t border-gray-100 text-xs">
                      <div>
                        <p className="font-bold text-text-primary mb-1">Industrial Benefits</p>
                        <ul className="list-disc pl-4 space-y-0.5 text-text-secondary">
                          {disc.industrial_benefits.map((b, i) => (
                            <li key={i}>{b}</li>
                          ))}
                        </ul>
                      </div>

                      <div>
                        <p className="font-bold text-text-primary mb-1">Environmental Benefits</p>
                        <ul className="list-disc pl-4 space-y-0.5 text-text-secondary">
                          {disc.environmental_benefits.map((b, i) => (
                            <li key={i}>{b}</li>
                          ))}
                        </ul>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Right sidebar general literature sources */}
          <div className="bg-white rounded-2xl p-6 shadow-card border border-gray-100/50 h-fit space-y-6">
            <h3 className="font-bold text-lg text-text-primary flex items-center gap-2">
              <GraduationCap className="text-primary-green" size={20} />
              Patent & Literature Sources
            </h3>

            <div className="space-y-4 text-xs leading-relaxed text-text-secondary">
              <div className="p-4 bg-gray-50 border border-gray-150 rounded-xl space-y-3">
                <p className="font-bold text-text-primary flex items-center gap-1.5">
                  <Scale size={16} className="text-deep-emerald" />
                  Technical Reference Standard:
                </p>
                <p>
                  Innovation pathways are matched using vector embeddings of patent logs and cross-referenced with live API searches from OpenAlex research registries.
                </p>
              </div>

              <div className="flex gap-2 text-text-muted">
                <Info size={16} className="text-deep-emerald flex-shrink-0 mt-0.5" />
                <p>
                  Technology Readiness Levels (TRL) range from TRL 1 (basic principles) to TRL 9 (proven industrial operations).
                </p>
              </div>
            </div>
          </div>
        </div>
      ) : (
        <div className="bg-white border border-gray-100 rounded-2xl p-12 text-center max-w-lg mx-auto">
          <Lightbulb className="text-text-muted mx-auto mb-3" size={48} />
          <h3 className="font-bold text-lg text-text-primary">No Innovation Context</h3>
          <p className="text-text-secondary text-sm mt-1">
            Run a new waste profile analysis first, or select a past contract ID above to generate circular reuse ideas.
          </p>
        </div>
      )}
    </div>
  );
};
export default CircularInnovation;
